# Generated by Django 3.0.5 on 2020-05-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_subdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbmember',
            name='pb_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Subdivision'),
        ),
    ]
